#pragma once 
#include <string>
using namespace std;

#define HWND_MESSAGE     ((HWND)-3)

#define WM_CHANGE_SHADER_TYPE					WM_USER + 101

#define WM_REQUEST_SCENE_INFO 					WM_USER + 102
#define WM_REQUEST_BACKGROUND_INFO 	WM_USER + 103
#define WM_REQUEST_GIZMO_INFO				 	WM_USER + 104
#define WM_REQUEST_CHANGE_TEXTURE		WM_USER + 105
#define WM_REQUEST_ADD_TEXTURE				WM_USER + 106
#define WM_REQUEST_DELETE_TEXTURE			WM_USER + 107
#define WM_REQUEST_TEXTURE_OPERATION   WM_USER + 108

#define WM_SCENE_INFORMATION						WM_USER + 110
#define WM_ADD_ACTOR										WM_USER + 111
 
#define WM_REQUEST_CHANGE_MOVIEFRAME   WM_USER + 112
#define WM_REQUEST_CAPTURE_MOVIEFRAME  WM_USER + 113
#define WM_REQUEST_SET_CAPTURE						WM_USER + 214
#define WM_REQUEST_CANVAS_INFO					WM_USER + 215
#define WM_REQUEST_VIDEO									WM_USER + 216

#define WM_TIMER_PLAY		8306
#define WM_TIMER_STOP		8307

#define WM_REQUEST_CANVAS_SIZE					  	WM_USER + 219
#define WM_REQUEST_CANVAS_EFFECT				WM_USER + 220
#define WM_REQUEST_CANVAS_MORPH				WM_USER + 221

#define WM_REQUEST_ADD_MOVIE_EFFECT			WM_USER + 222
#define WM_REQUEST_DELETE_MOVIE_EFFECT	WM_USER + 223

#define WM_REQUEST_CHANGE_MOVIE_EFFECT WM_USER + 224

#define WM_REQUEST_ADD_PHOTO_EFFECT		WM_USER + 225
#define WM_REQUEST_DELETE_PHOTO_EFFECT	WM_USER + 226

//UI 
const int OUTPUTWND_OUTPUT = 2;
const int OUTPUTWND_TEXTURE = 3;

class IndexStringParam
{
public:
	int intValue;
	std::string  stringValue;

	IndexStringParam() {
		intValue = 0;
	}
};

class IndexIntParam
{
public:
	int intValue1;
	int intValue2;

	IndexIntParam() {
		intValue1 = intValue2 = 0;
	}
};


enum   eEvent
{
	EVENT_BEGIN,

	TRANFORM_PROPERTY_EVENT_BEGIN,
		
		TRANSFORM_TRANSLATION_BEGIN,
			TRANSFORM_TRANSLATION_X,
			TRANSFORM_TRANSLATION_Y,
			TRANSFORM_TRANSLATION_Z,
		TRANSFORM_TRANSLATION_END,

		TRANSFORM_ROTATION_BEGIN,
			TRANSFORM_ROTATION_X,
			TRANSFORM_ROTATION_Y,
			TRANSFORM_ROTATION_Z,
		TRANSFORM_ROTATION_END,

		TRANSFORM_SCALE_BEGIN,
			TRANSFORM_SCALE_X,
			TRANSFORM_SCALE_Y,
			TRANSFORM_SCALE_Z,
		TRANSFORM_SCALE_END,

	TRANFORM_PROPERTY_EVENT_END,

	MATERIAL_PROPERTY_EVENT_BEGIN,

			DIFFUSE_EVENT_BEGIN,
				DIFFUSE_EVENT,
			DIFFUSE_EVENT_END,

			SPECULAR_EVENT_BEGIN,
				SPECULAR_EVENT,
			SPECULAR_EVENT_END,

			AMBIENT_EVENT_BEGIN,
				AMBIENT_EVENT,
			AMBIENT_EVENT_END,

			EMISSIVE_EVENT_BEGIN,
				EMISSIVE_EVENT,
			EMISSIVE_EVENT_END,

			ALPHA_EVENT_BEGIN,
				ALPHA_EVENT,
			ALPHA_EVENT_END,

	MATERIAL_PROPERTY_EVENT_END,

	DATA_PROPERTY_EVENT_BEGIN,
		LIGHT_PROPERTY_EVENT_BEGIN,		

			LIGHT_POSITION_BEGIN,
				LIGHT_POSITION_X,
				LIGHT_POSITION_Y,
				LIGHT_POSITION_Z,
			LIGHT_POSITION_END,

		LIGHT_PROPERTY_EVENT_END,
		
	DATA_PROPERTY_EVENT_END,

	SCENE_PROPERTY_EVENT_BEGIN,

		SCENE_RENDERER_EVENT_BEGIN,
			SCENE_RENDERER_FILL,
			SCENE_RENDERER_SHADING,
		SCENE_RENDERER_EVENT_END,

	SCENE_PROPERTY_EVENT_END,

	GIZMO_PROPERTY_EVENT_BEGIN,
		GIZMO_CANVAS_EVENT_BEGIN,
			GIZMO_CANVAS_ENABLE_MARK,
			GIZMO_CANVAS_ENABLE_GUIDELINE,
		GIZMO_CANVAS_EVENT_END,
	GIZMO_PROPERTY_EVENT_END,
	////////////////////////////////////////////////////////////////////
	///Canvas Property
	CANVAS_PROPERTY_EVENT_BEGIN,

		CANVAS_SIZE_EVENT_BEGIN,
				CANVAS_SIZE_EVENT,
		CANVAS_SIZE_EVENT_END,

		CANVAS_EFFECT_EVENT_BEGIN,
			CANVAS_EFFECT_EVENT_RESERVED,
		CANVAS_EFFECT_EVENT_END,

		CANVAS_MORPH_EVENT_BEGIN,
			CANVAS_MORPH_EVENT_RESERVED,
		CANVAS_MORPH_EVENT_END,

	CANVAS_PROPERTY_EVENT_END,
	////////////////////////////////////////////////////////////////////
	///Movie Effect Property
	MOVIE_PROPERTY_EVENT_BEGIN,

		MOVIE_PROPERTY_BLUR_BEGIN,
			MOVIE_PROPERTY_BLUR_SIZE_X,
			MOVIE_PROPERTY_BLUR_SIZE_Y,
		MOVIE_PROPERTY_BLUR_END,

	MOVIE_PROPERTY_EVENT_END,
	////////////////////////////////////////////////////////////////////
	PHOTO_PROPERTY_EVENT_BEGIN,
		PHOTO_PROPERTY_ALPAH_BEGIN,
			PHOTO_PROPERTY_ALPAH_VALUE,
		PHOTO_PROPERTY_ALPAH_END,

		PHOTO_PROPERTY_BRIGHT_CONTRAST_BEGIN,
			PHOTO_PROPERTY_BRIGHT_VALUE,
			PHOTO_PROPERTY_CONTRAST_VALUE,
		PHOTO_PROPERTY_BRIGHT_CONTRAST_END,

		PHOTO_PROPERTY_GRAY_BEGIN,
			PHOTO_PROPERTY_GRAY_AVERAGE,
			PHOTO_PROPERTY_GRAY_NTSC,
			PHOTO_PROPERTY_GRAY_HSV,
			PHOTO_PROPERTY_GRAY_DESATURATION,
			PHOTO_PROPERTY_GRAY_DECOMPOSITION_MAX,
			PHOTO_PROPERTY_GRAY_DECOMPOSITION_MIN,
		PHOTO_PROPERTY_GRAY_END,

	PHOTO_PROPERTY_EVENT_END,
	////////////////////////////////////////////////////////////////////
	EVENT_END,
};

