#pragma once

//enum eMapperType
//{
//	MAPPTER_2D_TRIANGLE,
//	MAPPTER_2D_RECTANGLE,
//	MAPPTER_2D_CIRCLE,
//	MAPPTER_2D_LINE,
//
//	MAPPTER_3D_CUBE,
//	MAPPTER_3D_SPHERE,
//	MAPPTER_3D_PLANE,
//	MAPPTER_3D_CYLINDER,
//};

enum eFillMode{
	FILLMODE_WIREFRAME,
	FILLMODE_SOLID,

	FILLMODE_COUNT,
};

enum eShadingModel{
	SHADING_MODEL_FLAT,
	SHADING_MODEL_SMOOTH,

	SHAINDG_MODEL_COUNT,
};

enum eGizmo{
	GIZMO_ROTATION_X,
	GIZMO_ROTATION_Y,
	GIZMO_ROTATION_Z,
	GIZMO_LIGHT,
	GIZMO_LIGHT_ARROW,

	GIZMO_COUNT
};

enum eAlgorithmType
{
	ALGORITHM_TYPE_BEZIER,

};

enum eSceneType
{
	SCENE_TYPE_PROTOTYPE,
	SCENE_TYPE_DEMO1,
	SCENE_TYPE_DEMO2,
	SCENE_TYPE_DEMO3,
	SCENE_TYPE_2D,

	SCENE_TYPE_MOVIE,
};

enum eSourceType
{//P : Position, N : Normal, C : Color, T: Texel
	SOURCE_2D_BEGIN,
		SOURCE_2D_TRIANGLE_PC,
		SOURCE_2D_RECTANGLE_PC,
		SOURCE_2D_CIRCLE_PC,
		SOURCE_2D_LINE_PC,

		SOURCE_2D_TRIANGLE_PTC,
		SOURCE_2D_RECTANGLE_PTC,		
		SOURCE_2D_CIRCLE_PTC,
		SOURCE_2D_LINE_PTC,

		SOURCE_2D_MOVIE_RECTANGLE_PTC,
	SOURCE_2D_END,

	SOURCE_3D_BEGIN,
		SOURCE_3D_CUBE_PC,
		SOURCE_3D_SPHERE_PC,
		SOURCE_3D_PLANE_PC,
		SOURCE_3D_CYLINDER_PC,

		SOURCE_3D_CUBE_PNC,
		SOURCE_3D_SPHERE_PNC,
		SOURCE_3D_PLANE_PNC,
		SOURCE_3D_CYLINDER_PNC,
	SOURCE_3D_END,


	SOURCE_UNKNOWN,
};

enum eShapeType
{
	SHAPE_3D_SPHERE,

	SHAPE_UNKNOWN,
};


enum eDrawElementType
{
	ELEMENT_TYPE_LINES,
	ELEMENT_TYPE_TRIANGLES,
	ELEMENT_TYPE_TRIANGLE_STRIP,
	ELEMENT_TYPE_TRIANGLE_FAN,
	ELEMENT_TYPE_QUADS,
	ELEMENT_TYPE_QUADS_STRIP,
	ELEMENT_TYPE_POINTS,

};

enum eVertexType
{
	VERTEX_POSITION = 1 << 0,
	VERTEX_NORMAL = 1 << 1,
	VERTEX_COLOR = 1 << 2,
	VERTEX_TEX0 = 1 << 3,

	VERTEX_XYZ_COLOR = VERTEX_POSITION | VERTEX_COLOR,
	VERTEX_XYZ_NORMAL_DIFFUSE = VERTEX_POSITION | VERTEX_NORMAL | VERTEX_COLOR,
	VERTEX_XYZ_TEX0 = VERTEX_POSITION | VERTEX_TEX0,
	VERTEX_XYZ_COLOR_TEX0 = VERTEX_POSITION | VERTEX_COLOR | VERTEX_TEX0,
	VERTEX_XYZ_NORMAL_TEX0 = VERTEX_POSITION | VERTEX_NORMAL | VERTEX_TEX0,

	VERTEX_SELECTED = 9900,
	VERTEX_UNKNOWN = 9999,
};

enum eSOILReadableImageType
{
	SOIL_IMAGE_READ_BMP,
	SOIL_IMAGE_READ_PNG,
	SOIL_IMAGE_READ_JPG,
	SOIL_IMAGE_READ_TGA,
	SOIL_IMAGE_READ_DDS,
	SOIL_IMAGE_READ_PSD,
	SOIL_IMAGE_READ_HDR,
	SOIL_IMAGE_READ_UNSUPPORTED,
};

enum eSOILWritableImageType
{
	SOIL_IMAGE_WRITE_BMP,
	SOIL_IMAGE_WRITE_TGA,
	SOIL_IMAGE_WRITE_DDS,
	SOIL_IMAGE_WRITE_UNSUPPORTED,
};

enum eInformationTarget
{
	INFO_TARGET_OUTWND_BEGIN,
		INFO_TARGET_OUTWND_OUTPUT,	
	INFO_TARGET_OUTWND_END,

	INFO_TARGET_OBJECT_BEGIN,
		INFO_TARGET_OBJECT_ADD,
	INFO_TARGET_OBJECT_END,

	INFO_TARGET_PROPERTY_BEGIN,
		INFO_TARGET_PROPERTY_RENDERER,
	INFO_TARGET_PROPERTY_END,

	INFO_TARGET_GIZMO_BEGIN,
		INFO_TARGET_GIZMO_ADD,
	INFO_TARGET_GIZMO_END,

	INFO_TARGET_CANVAS_BEGIN,
		INFO_TARGET_CANVAS_INFO,
	INFO_TARGET_CANVAS_END,
};


enum eShaderFactory
{//P : Position, N : Normal, C : Color, T: Texel
	SHADER_VERTEX_BEGIN,
		SHADER_VERTEX_SIMPLE_PC,
		SHADER_VERTEX_SIMPLE_PNC,
		SHADER_VERTEX_SIMPLE_PTC,

		SHADER_VERTEX_SELECTED,
	SHADER_VERTEX_END,

	SHADER_TESSELLATION_BEGIN,
	SHADER_TESSELLATION_END,

	SHADER_GEOMETRY_BEGIN,
	SHADER_GEOMETRY_END,

	SHADER_FRAGMENT_BEGIN,
		SHADER_FRAGMENT_SIMPLE_PC,
		SHADER_FRAGMENT_SIMPLE_PNC,
		SHADER_FRAGMENT_SIMPLE_PTC,

		SHADER_FRAGMENT_SELECTED,

		//PP:Post Process
		SHADER_FRAGMENT_PP_ALPHA, 
		SHADER_FRAGMENT_PP_CONTRAST_BRIGHT,
		SHADER_FRAGMENT_PP_GRAY,
		//////////////////////////////////////////////////////////////////
	SHADER_FRAGMENT_END,

	SHADER_COMPUTE_BEGIN,
	SHADER_COMPUTE_END,	
};

enum eShaderType
{
	SHADER_TYPE_SIMPLE_PC,
	SHADER_TYPE_SIMPLE_PTC,
	SHADER_TYPE_PHONG,	

	SHADER_TYPE_UNKNOWN,
};

enum eGLSLShaderType
{
	SHADER_TYPE_VERTEX,
	SHADER_TYPE_FRAGMENT,
	SHADER_TYPE_TESSELLATION,
	SHADER_TYPE_COMPUTE,
};

enum eCanvasSize
{
	CANVAS_TYPE_FULL,
	CANVAS_TYPE_0_9x,
	CANVAS_TYPE_0_8x,
	CANVAS_TYPE_0_7x,
	CANVAS_TYPE_0_6x,
	CANVAS_TYPE_0_5x,
	CANVAS_TYPE_0_4x,
	CANVAS_TYPE_0_3x,

	CANVAS_TYPE_NUM,
};

enum eCanvasEffect
{
	CANVAS_EFFECT_RESERVED,
};

enum eCanvasMorph
{
	CANVAS_MORPH_RESERVED,
};

enum eMovieEffect
{
	MOVIE_EFFECT_BLUR,
	MOVIE_EFFECT_ERODE,

	MOVIE_EFFECT_NUM,
};

enum ePhotoEffect
{
	PHOTO_EFFECT_ALPHA,
	PHOTO_EFFECT_BRIGHT_CONTRAST,
	PHOTO_EFFECT_GRAY,

	PHOTO_EFFECT_NUM,
};

enum eSpecialEffect
{
	SPECIAL_EFFECT_2DTO3D_01,
	SPECIAL_EFFECT_MATRYOSHKA_ALBUM,
};

enum ePhotoSpecialEffect
{
	PHOTO_SPECIAL_EFFECT_MATRYOSHKA_ALBUM,
	PHOTO_SPECIAL_EFFECT_2D_TO_3D_CONVERSION_01,

	PHOTO_SPECIAL_EFFECT_NUM,
};


enum eTextureOperation
{
	TEXTURE_OPERATION_MODULATE,
	TEXTURE_OPERATION_ADD,
	TEXTURE_OPERATION_DARKEN,
	TEXTURE_OPERATION_LIGHTEN,
	TEXTURE_OPERATION_SUBTRACT,
	TEXTURE_OPERATION_DIFFERENCE,
};


enum eTimer
{
	TIMER_MOVIE_PLAY = 1,
};