#pragma once

extern LPCTSTR  STRING_PROGRAM_NAME;
extern LPCTSTR STRING_MODEL_GROUP;
extern LPCTSTR STRING_LIGHT_GROUP;
extern LPCTSTR STRING_CAMERA_GROUP;
extern LPCTSTR STRING_OBJECT;
extern LPCTSTR STRING_MODEL;
extern LPCTSTR STRING_LIGHT;
extern LPCTSTR STRING_CAMERA;

extern LPCTSTR STRING_NAME;

extern LPCTSTR STRING_POSITION;
extern LPCTSTR STRING_ROTATION;
extern LPCTSTR STRING_SCALE;

extern LPCTSTR STRING_OBJ_EXTENSION;
extern LPCTSTR STRING_3DS_EXTENSION;
extern LPCTSTR STRING_MD2_EXTENSION;
extern LPCTSTR STRING_MD3_EXTENSION;
extern LPCTSTR STRING_COLLADA_EXTENSION;
extern LPCTSTR STRING_STL_EXTENSION;

extern LPCTSTR STRING_BMP_EXTENSION;
extern LPCTSTR STRING_IMPORT_3D_FILTER;
extern LPCTSTR STRING_IMPORT_IMG_FILTER;
extern LPCTSTR STRING_TERRAIN_RAW_FORMAT;

extern LPCTSTR STRING_SHADING_MODEL[];
extern LPCTSTR STRING_FILL_MODE[];
extern LPCTSTR STRING_PICKING_MODE[];

extern LPCTSTR STRING_OBJECT_TRANS;
extern LPCTSTR STRING_OBJECT_TRANSLATION;
extern LPCTSTR STRING_OBJECT_ROTATION;
extern LPCTSTR STRING_OBJECT_SCALE;

extern LPCTSTR STRING_MATERIAL_PROPERTY;
extern LPCTSTR STRING_MATERIAL_COLOR;
extern LPCTSTR STRING_MATERIAL_DIFFUSE;
extern LPCTSTR STRING_MATERIAL_SPECULAR;
extern LPCTSTR STRING_MATERIAL_AMBIENT;
extern LPCTSTR STRING_MATERIAL_EMISSIVE;
extern LPCTSTR STRING_MATERIAL_ALPHA;

extern	LPCTSTR  STRING_SHADER_ALGORITHM_NONE;
extern	LPCTSTR	STRING_SHADER_ALGORITHM_SHADOW_BEGIN;
extern LPCTSTR  STRING_SHADER_FIXED_PIPE_SHADOW_MAP;
extern	LPCTSTR  STRING_SHADER_PROJECTED_SHADOW;
extern	LPCTSTR  STRING_SHADER_STENCIL_SHADOW;
extern	LPCTSTR  STRING_SHADER_DEPTH_BUFFER_SHADOW;
extern	LPCTSTR  STRING_SHADER_PSM;
extern	LPCTSTR  STRING_SHADER_LSPSM;
extern	LPCTSTR  STRING_SHADER_CASCADED_LSPSM;
extern	LPCTSTR  STRING_SHADER_SOFT_SHADOW;
extern	LPCTSTR  STRING_SHADER_VSM;
extern	LPCTSTR  STRING_SHADER_ALGORITHM_SHADOW_END;

extern	LPCTSTR  STRING_LIGHT_POSITON;
extern	LPCTSTR  STRING_SHADOW_POLYGON_OFFSET;
extern	LPCTSTR  STRING_SHADOW_MAP_SIZE;

extern	LPCTSTR	 STRING_SHADER_PROPERTY;
extern	LPCTSTR	 STRING_SHADOW_LIGHTNESS;
extern  LPCTSTR  STRING_SHADOW_ACCESSIBILITY;

extern  LPCTSTR  STRING_TEXTURE_NAME;

extern LPCTSTR STRING_SCENE_RENDERER;
extern LPCTSTR STRING_SCENE_RENDERER_FILL;
extern LPCTSTR STRING_SCENE_RENDERER_SHADING;

extern LPCTSTR STRING_CANVAS_NAME;
extern LPCTSTR STRING_CANVAS_SIZE[];

extern LPCTSTR STRING_CANVAS_EFFECT;
extern LPCTSTR STRING_CANVAS_MORPH;

extern LPCTSTR STRING_MOVIE_EFFECT[];
extern LPCTSTR STRING_MOVIE_EFFECT_NAME;

extern LPCTSTR STRING_PHOTO_EFFECT[];
extern LPCTSTR STRING_PHOTO_EFFECT_NAME;
extern LPCTSTR STRING_PHOTO_EFFECT_GRAY_NAME;
extern LPCTSTR STRING_PHOTO_EFFECT_GRAY[];


extern LPCTSTR STRING_PHOTO_SPECIAL_EFFECT[];
extern LPCTSTR STRING_PHOTO_SPECIAL_EFFECT_NAME;
